/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.busca;

import Conexao.conexao;
import Model.cadastro.ModalCliente;
import Model.table.cadastro.TableModelCliente;
import Util.Verificar.VerificarUsuario;
import Visao.processo.frm_hospedagem;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class frm_busca_clientes extends javax.swing.JInternalFrame {

    TableModelCliente tableModelCliente = new TableModelCliente();
    VerificarUsuario verificarUsuario = new VerificarUsuario();
    public static frm_busca_clientes instance = null;
    conexao conn = new conexao();
    private static frm_busca_clientes frm_busca_clientes;
    String telaPai = "", sqlInicial = "";

    /**
     * Creates new form frm_cliente
     *
     * @param telaPai
     * @param sqlInicial
     * @return
     */
    public static frm_busca_clientes getInstancia(String telaPai, String sqlInicial) {
        if (frm_busca_clientes == null) {
            frm_busca_clientes = new frm_busca_clientes(telaPai, sqlInicial);
        }
        return frm_busca_clientes;
    }

    public frm_busca_clientes(String telaPai, String sqlInicial) {
        initComponents();
        this.telaPai = telaPai;
        this.sqlInicial = sqlInicial;
        jTableConsulta.setModel(tableModelCliente);
        atualizaTabela(sqlInicial);
        jButtonLimparBusca.setVisible(false);
        jLabelVariavalBusca.setText("Nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBusca = new javax.swing.JLabel();
        jLabelVariavalBusca = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonLimparBusca = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();

        setClosable(true);
        setTitle("Buscar Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelBusca.setText("Buscar por");

        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyReleased(evt);
            }
        });

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Browser-Search.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonLimparBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Browser-Remove.png"))); // NOI18N
        jButtonLimparBusca.setText("Limpar");
        jButtonLimparBusca.setToolTipText("Buscar");
        jButtonLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparBuscaActionPerformed(evt);
            }
        });

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLimparBusca))
                            .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVariavalBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVariavalBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimparBusca)
                    .addComponent(jButtonBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyPressed

    }//GEN-LAST:event_jTextFieldBuscaKeyPressed

    private void jTextFieldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyReleased

    }//GEN-LAST:event_jTextFieldBuscaKeyReleased

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if (jTextFieldBusca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o que você está procurando antes de proceguir.");
        } else {
            if (telaPai.equals("Hospedagem")) {
                atualizaTabela("SELECT cliente_id, cliente_nome, "
                        + "cliente_cpf_cnpj FROM tbl_cliente WHERE "
                        + "cliente_" + jLabelVariavalBusca.getText() + " "
                        + "LIKE '%" + jTextFieldBusca.getText() + "%' AND LENGTH(cliente_cpf_cnpj) = 14");
            } else if (telaPai.equals("Hospedagem Cliente")) {
                atualizaTabela("SELECT cliente_id, cliente_nome, "
                        + "cliente_cpf_cnpj FROM tbl_cliente WHERE "
                        + "cliente_" + jLabelVariavalBusca.getText() + " "
                        + "LIKE '%" + jTextFieldBusca.getText() + "%' AND LENGTH(cliente_cpf_cnpj) = 11");

            }
            jButtonLimparBusca.setVisible(true);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparBuscaActionPerformed
        atualizaTabela(sqlInicial);
        jTextFieldBusca.setText("");
        jButtonLimparBusca.setVisible(false);
    }//GEN-LAST:event_jButtonLimparBuscaActionPerformed

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        if (evt.getClickCount() == 2) {
            String id = String.valueOf(jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 0));
            String nome = String.valueOf(jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 1));
            if (telaPai.equals("Hospedagem")) {
                frm_hospedagem.setReceberClienteEmpresa(id, nome);
                dispose();
            } else if (telaPai.equals("Hospedagem Cliente")) {
                frm_hospedagem.setReceberCliente(id, nome);
                dispose();
            }
        }
    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void jTableConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseReleased
        jLabelVariavalBusca.setText(jTableConsulta.getColumnName(jTableConsulta.getSelectedColumn()));
    }//GEN-LAST:event_jTableConsultaMouseReleased

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        frm_busca_clientes = null;
    }//GEN-LAST:event_formInternalFrameClosed

    public void atualizaTabela(String sql) {
        tableModelCliente.dados.removeAll(tableModelCliente.dados);
        conn.executaSQL(sql);
        try {
            while (conn.rs.next()) {
                ModalCliente modalQ = new ModalCliente();

                modalQ.setId(conn.rs.getInt("cliente_id"));
                modalQ.setNome(conn.rs.getString("cliente_nome"));
                modalQ.setCpfCnpj(conn.rs.getString("cliente_cpf_cnpj"));
                tableModelCliente.addRow(modalQ);

            }
            conn.rs.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonLimparBusca;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelVariavalBusca;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
