/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.cadastro;

import Conexao.conexao;
import DAO.cadastro.DAOProduto;
import Model.cadastro.ModalProduto;
import Model.table.TableModelQuantidadeProdutos;
import Model.table.cadastro.TableModelProduto;
import Util.LimpaCampos;
import Util.Maiusculo;
import Util.somenteNumeros;
import Visao.v_principal;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class frm_produto extends javax.swing.JInternalFrame {

    TableModelQuantidadeProdutos modelQuantidadeProdutos = new TableModelQuantidadeProdutos();
    ModalProduto modalProduto = new ModalProduto();
    DAOProduto daoProduto = new DAOProduto();
    TableModelProduto tableModelProduto = new TableModelProduto();
    conexao conn = new conexao();
    int flagCamposVazios = 0, flag = 0;
    Color color = new Color(56, 176, 222);
    Color colorPadrao = new Color(255, 255, 255);
    private static frm_produto frm_produto;

    /**
     * Creates new form frm_produto
     */
    public static frm_produto getInstancia() {
        if (frm_produto == null) {
            frm_produto = new frm_produto();
        }
        return frm_produto;
    }

    public frm_produto() {
        initComponents();
        esquemaBotoesInicio();
        CardLayout cl = (CardLayout) jPanelGeral.getLayout();
        cl.show(jPanelGeral, "consulta");
        jTableConsulta.setModel(tableModelProduto);
        atualizaTabela("select * from tbl_produto");
        jTextFieldQuantidadeProduto.setDocument(new somenteNumeros());
        jLabelVariavalBusca.setText("Nome");

        maiusculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeral = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNumeroQuarto = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldQuantidadeProduto = new javax.swing.JTextField();
        jLabelAndarQuarto = new javax.swing.JLabel();
        jTextFieldValorProduto = new javax.swing.JTextField();
        jLabelValorDiaria = new javax.swing.JLabel();
        jLabelDinheiroReal = new javax.swing.JLabel();
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabelBusca = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonLimparBusca = new javax.swing.JButton();
        jLabelVariavalBusca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Produtos");
        setToolTipText("Cadastro de Produtos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanelGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelGeral.setLayout(new java.awt.CardLayout());

        jPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCodigo.setText("Código");

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setEnabled(false);

        jLabelNumeroQuarto.setText("Nome");

        jLabelAndarQuarto.setText("Quantidade");

        jTextFieldValorProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorProdutoFocusLost(evt);
            }
        });

        jLabelValorDiaria.setText("Valor");

        jLabelDinheiroReal.setText("R$");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabelNumeroQuarto)
                                .addGap(0, 202, Short.MAX_VALUE))
                            .addComponent(jTextFieldNomeProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAndarQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabelDinheiroReal)
                                .addGap(3, 3, 3)
                                .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelNumeroQuarto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabelAndarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorDiaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDinheiroReal))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jPanelGeral.add(jPanelCadastro, "cadastro");

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableConsulta);

        jLabelBusca.setText("Buscar por");

        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyReleased(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonLimparBusca.setText("Limpar");
        jButtonLimparBusca.setToolTipText("Buscar");
        jButtonLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jLabelBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVariavalBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButtonBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimparBusca)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBusca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVariavalBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBuscar)
                        .addComponent(jButtonLimparBusca))
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanelGeral.add(jPanelConsulta, "consulta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE PRODUTOS");

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Box-Incoming.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Repeat.png"))); // NOI18N
        jButtonAlterar.setToolTipText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Remove.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Relatorio3.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorProdutoFocusLost

    }//GEN-LAST:event_jTextFieldValorProdutoFocusLost

    private void jTableConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseReleased
        jLabelVariavalBusca.setText(jTableConsulta.getColumnName(jTableConsulta.getSelectedColumn()));
    }//GEN-LAST:event_jTableConsultaMouseReleased

    private void jTextFieldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyPressed

    }//GEN-LAST:event_jTextFieldBuscaKeyPressed

    private void jTextFieldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyReleased

    }//GEN-LAST:event_jTextFieldBuscaKeyReleased

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if (jTextFieldBusca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o que você está procurando antes de proceguir.");
        } else {
            atualizaTabela("SELECT * FROM tbl_produto WHERE "
                    + "produto_" + jLabelVariavalBusca.getText() + " "
                    + "LIKE '%" + jTextFieldBusca.getText() + "%'");
            jButtonLimparBusca.setVisible(true);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparBuscaActionPerformed
        atualizaTabela("select * from tbl_produto");
        jTextFieldBusca.setText("");
        jButtonLimparBusca.setVisible(false);
    }//GEN-LAST:event_jButtonLimparBuscaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        esquemaBotoesSalvar();
        flag = 1;
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        verificaCamposVazios();
        if (flagCamposVazios == 1) {
            modalProduto.setNome(jTextFieldNomeProduto.getText());
            modalProduto.setValor(Double.parseDouble(jTextFieldValorProduto.getText()));
            modalProduto.setQuantidade(Integer.parseInt(jTextFieldQuantidadeProduto.getText()));
            if (flag == 1) {
                try {
                    daoProduto.create(modalProduto);
                    esquemaBotoesInicio();
                    limpaCampos();
                    atualizaTabela("select * from tbl_produto");
                    conn.rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(frm_produto.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                modalProduto.setId(Integer.parseInt(jTextFieldCodigo.getText()));
                try {
                    daoProduto.update(modalProduto);
                    esquemaBotoesInicio();
                    limpaCampos();
                    atualizaTabela("select * from tbl_produto");
                    conn.rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(frm_produto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        if (jTableConsulta.getSelectedRow() != -1) {
            jTextFieldCodigo.setText(jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 0).toString());
            jTextFieldNomeProduto.setText(jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 1).toString());
            jTextFieldQuantidadeProduto.setText(jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 3).toString());
            conn.executaSQL("SELECT produto_valor FROM tbl_produto WHERE produto_id = " + jTextFieldCodigo.getText());
            try {
                if (conn.rs.next()) {
                    jTextFieldValorProduto.setText(String.valueOf(conn.rs.getDouble("produto_valor")));
                }
                conn.rs.close();
            } catch (SQLException ex) {

            }
            esquemaBotoesSalvar();
        } else {
            JOptionPane.showMessageDialog(null, "Para alterar, selecione algum item.");
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        esquemaBotoesInicio();
        limpaCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        frm_produto = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void esquemaBotoesInicio() {
        jButtonCancelar.setVisible(false);
        jButtonSalvar.setVisible(false);
        jButtonNovo.setVisible(true);
        jButtonAlterar.setVisible(true);
        CardLayout cl = (CardLayout) jPanelGeral.getLayout();
        cl.show(jPanelGeral, "consulta");
    }

    private void esquemaBotoesSalvar() {
        jButtonCancelar.setVisible(true);
        jButtonSalvar.setVisible(true);
        jButtonNovo.setVisible(false);
        jButtonAlterar.setVisible(false);
        CardLayout cl = (CardLayout) jPanelGeral.getLayout();
        cl.show(jPanelGeral, "cadastro");
    }

    private void verificaCamposVazios() {
        if (jTextFieldNomeProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Nome, está em branco");
            jTextFieldNomeProduto.requestFocus();
            jTextFieldNomeProduto.setBackground(color);
        } else {
            jTextFieldNomeProduto.setBackground(colorPadrao);
        }
        if (jTextFieldQuantidadeProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Quantidade, está em branco");
            jTextFieldQuantidadeProduto.requestFocus();
            jTextFieldQuantidadeProduto.setBackground(color);
        } else {
            jTextFieldQuantidadeProduto.setBackground(colorPadrao);
        }
        if (jTextFieldValorProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Valor do Produto, está em branco");
            jTextFieldValorProduto.requestFocus();
            jTextFieldValorProduto.setBackground(color);
        } else {
            jTextFieldValorProduto.setBackground(colorPadrao);
        }
        if (jTextFieldNomeProduto.getBackground() == colorPadrao
                && jTextFieldQuantidadeProduto.getBackground() == colorPadrao
                && jTextFieldValorProduto.getBackground() == colorPadrao) {
            flagCamposVazios = 1;
        } else {
            flagCamposVazios = 0;
        }
    }

    private void limpaCampos() {
        LimpaCampos.limpaCampos(jPanelCadastro.getComponents());
    }

    public void atualizaTabela(String sql) {
        tableModelProduto.dados.removeAll(tableModelProduto.dados);
        conn.executaSQL(sql);
        try {
            while (conn.rs.next()) {
                ModalProduto modalQ = new ModalProduto();

                modalQ.setId(conn.rs.getInt("produto_id"));
                modalQ.setNome(conn.rs.getString("produto_nome"));
                modalQ.setValor(conn.rs.getDouble("produto_valor"));
                modalQ.setQuantidade(conn.rs.getInt("produto_quantidade"));
                tableModelProduto.addRow(modalQ);

            }
            conn.rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_produto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void maiusculo() {
        jTextFieldNomeProduto.setDocument(new Maiusculo());
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimparBusca;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAndarQuarto;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDinheiroReal;
    private javax.swing.JLabel jLabelNumeroQuarto;
    private javax.swing.JLabel jLabelValorDiaria;
    private javax.swing.JLabel jLabelVariavalBusca;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldQuantidadeProduto;
    private javax.swing.JTextField jTextFieldValorProduto;
    // End of variables declaration//GEN-END:variables
}
