/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.cadastro;

import Conexao.ConexaoHttp;
import Conexao.conexao;
import DAO.cadastro.DAOCliente;
import Model.cadastro.ModalCliente;
import Model.table.cadastro.TableModelCliente;
import Util.CNPJ;
import Util.CPF;
import Util.LimpaCampos;
import Util.Maiusculo;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class frm_cliente extends javax.swing.JInternalFrame {

    TableModelCliente tableModelCliente = new TableModelCliente();
    ModalCliente modalCliente = new ModalCliente();
    DAOCliente daoCliente = new DAOCliente();
    conexao conn = new conexao();
    int flagCamposVazios = 0, flag = 0, flagSalvaVeiculo = 0, flagCamposVaziosVeiculo = 0, flagVerifica = 0,
            flagComplemento = 0;
    Color color = new Color(56, 176, 222);
    Color colorPadrao = new Color(255, 255, 255);
    private static frm_cliente frm_cliente;
    String cnpj;
    ArrayList<Object> ap = new ArrayList<>();

    /**
     * Creates new form frm_cliente
     */
    public static frm_cliente getInstancia() {
        if (frm_cliente == null) {
            frm_cliente = new frm_cliente();
        }
        return frm_cliente;
    }

    public frm_cliente() {
        initComponents();
        esquemaBotoesInicio();
        CardLayout cl = (CardLayout) jPanelGeral.getLayout();
        cl.show(jPanelGeral, "consulta");
        jTableConsulta.setModel(tableModelCliente);
        atualizaTabela("SELECT cliente_id, cliente_nome, cliente_cpf_cnpj FROM tbl_cliente");
        maiusculo();
        jLabelVariavalBusca.setText("Nome");
        jCheckBoxPessoaFisica.setSelected(true);
        
        mudaTipoPessoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelGeral = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jPanelEndereco = new javax.swing.JPanel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabeNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jComboBoxUF = new javax.swing.JComboBox();
        jLabelUF = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabeCelular = new javax.swing.JLabel();
        jCheckBoxPessoaFisica = new javax.swing.JCheckBox();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JFormattedTextField();
        jTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jLabelCNPJ = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jLabelRazaoSocial = new javax.swing.JLabel();
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabelBusca = new javax.swing.JLabel();
        jLabelVariavalBusca = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonLimparBusca = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Clientes");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE CLIENTES");

        jPanelGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelGeral.setLayout(new java.awt.CardLayout());

        jLabelCodigo.setText("Código");

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setEnabled(false);

        jLabelNome.setText("Nome Completo");

        jLabel5.setText("RG");

        jPanelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabelEndereco.setText("Logradouro");

        jLabeNumero.setText("Número");

        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFActionPerformed(evt);
            }
        });

        jLabelUF.setText("UF");

        jLabelCidade.setText("Cidade");

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jLabelBairro.setText("Bairro");

        jLabelComplemento.setText("Complemento");

        try {
            jTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCEP.setText("CEP");

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBairro)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUF)))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeNumero)))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelComplemento)
                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCEP)
                            .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabeNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelUF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try {
            jTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabeCelular.setText("Celular");

        jCheckBoxPessoaFisica.setText("É pessoa física?");
        jCheckBoxPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPessoaFisicaActionPerformed(evt);
            }
        });

        jLabelCPF.setText("CPF");

        try {
            jTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCPFFocusLost(evt);
            }
        });

        try {
            jTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCNPJFocusLost(evt);
            }
        });
        jTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCNPJActionPerformed(evt);
            }
        });

        jLabelCNPJ.setText("CNPJ");

        jLabelRazaoSocial.setText("Razão Social");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRazaoSocial)
                            .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jCheckBoxPessoaFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPF)
                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCNPJ)
                            .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeCelular)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelRazaoSocial)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCodigo)
                                .addComponent(jLabelNome))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabeCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jCheckBoxPessoaFisica))
                        .addGroup(jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelCPF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelCNPJ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanelGeral.add(jPanelCadastro, "cadastro");

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableConsulta);

        jLabelBusca.setText("Buscar por");

        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyReleased(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonLimparBusca.setText("Limpar");
        jButtonLimparBusca.setToolTipText("Buscar");
        jButtonLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jLabelBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVariavalBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimparBusca)
                        .addGap(4, 4, 4))))
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVariavalBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonLimparBusca))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jPanelGeral.add(jPanelConsulta, "consulta");

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Box-Incoming.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Repeat.png"))); // NOI18N
        jButtonAlterar.setToolTipText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Remove.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Relatorio3.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked

    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void jTableConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseReleased
        jLabelVariavalBusca.setText(jTableConsulta.getColumnName(jTableConsulta.getSelectedColumn()));
    }//GEN-LAST:event_jTableConsultaMouseReleased

    private void jTextFieldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyPressed

    }//GEN-LAST:event_jTextFieldBuscaKeyPressed

    private void jTextFieldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyReleased

    }//GEN-LAST:event_jTextFieldBuscaKeyReleased

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if (jTextFieldBusca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o que você está procurando antes de proceguir.");
        } else {
            atualizaTabela("SELECT cliente_id, cliente_nome, "
                    + "cliente_cpf_cnpj FROM tbl_cliente WHERE "
                    + "cliente_" + jLabelVariavalBusca.getText() + " "
                    + "LIKE '%" + jTextFieldBusca.getText() + "%'");
            jButtonLimparBusca.setVisible(true);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparBuscaActionPerformed
        atualizaTabela("SELECT cliente_id, cliente_nome, cliente_cpf_cnpj FROM tbl_cliente");
        jTextFieldBusca.setText("");
        jButtonLimparBusca.setVisible(false);
    }//GEN-LAST:event_jButtonLimparBuscaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        esquemaBotoesSalvar();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        verificaCamposVazios();
        if (flagCamposVazios == 1) {
            modalCliente.setNome(jTextFieldNome.getText());
            if (jCheckBoxPessoaFisica.isSelected()) {
                modalCliente.setCpfCnpj(jTextFieldCPF.getText().replaceAll("[()./-]", ""));
            } else {
                modalCliente.setCpfCnpj(jTextFieldCNPJ.getText().replaceAll("[()./-]", ""));
                modalCliente.setRazaoSocial(jTextFieldRazaoSocial.getText());
            }

            modalCliente.setRg(jTextFieldRG.getText());
            modalCliente.setLogradouro(jTextFieldEndereco.getText());
            modalCliente.setNumero(jTextFieldNumero.getText());
            modalCliente.setBairro(jTextFieldBairro.getText());
            modalCliente.setCidade(jTextFieldCidade.getText());
            modalCliente.setEstado(jComboBoxUF.getSelectedItem().toString());
            modalCliente.setCelular(jTextFieldTelefone.getText().replaceAll("[()./-]", ""));
            modalCliente.setComplemento(jTextFieldComplemento.getText());
            modalCliente.setCep(jTextFieldCEP.getText().replaceAll("[./-]", ""));
            if (flag == 1) {
                if (jCheckBoxPessoaFisica.isSelected()) {
                    conn.executaSQL("SELECT cliente_id FROM tbl_cliente WHERE cliente_cpf_cnpj = '"
                            + jTextFieldCPF.getText().replaceAll("[()./-]", "") + "'");
                } else {
                    conn.executaSQL("SELECT cliente_id FROM tbl_cliente WHERE cliente_cpf_cnpj = '"
                            + jTextFieldCNPJ.getText().replaceAll("[()./-]", "") + "'");
                }
                try {
                    if (conn.rs.next()) {
                        do {
                            JOptionPane.showMessageDialog(rootPane, "Cliente já cadastrado! \nSeu código é " + conn.rs.getInt("cliente_id"));
                            jTextFieldNome.requestFocus();
                            jTextFieldNome.setBackground(color);
                            flagVerifica = 1;
                        } while (conn.rs.next());
                    } else {
                        daoCliente.create(modalCliente);
                        atualizaTabela("SELECT cliente_id, cliente_nome, cliente_cpf_cnpj FROM tbl_cliente");
                        limpaCampos();
                        esquemaBotoesInicio();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frm_cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                modalCliente.setId(Integer.parseInt(jTextFieldCodigo.getText()));
                try {
                    daoCliente.update(modalCliente);
                    atualizaTabela("SELECT cliente_id, cliente_nome, cliente_cpf_cnpj FROM tbl_cliente");
                    limpaCampos();
                    esquemaBotoesInicio();
                } catch (SQLException ex) {
                    Logger.getLogger(frm_cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        if (jTableConsulta.getSelectedRow() != -1) {
            jTextFieldCodigo.setText(jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 0).toString());
            conn.executaSQL("SELECT * FROM tbl_cliente WHERE cliente_id = " + jTextFieldCodigo.getText());
            try {
                if (conn.rs.next()) {
                    jCheckBoxPessoaFisica.setEnabled(false);
                    jTextFieldCNPJ.setEnabled(false);
                    jTextFieldCPF.setEnabled(false);
                    jComboBoxUF.setSelectedItem(conn.rs.getString("cliente_endereco_estado"));
                    jTextFieldBairro.setText(conn.rs.getString("cliente_endereco_bairro"));
                    jTextFieldCEP.setText(conn.rs.getString("cliente_endereco_cep"));
                    String recebeCpfCnpj = conn.rs.getString("cliente_cpf_cnpj");
                    if (recebeCpfCnpj.length() == 11) {
                        jCheckBoxPessoaFisica.setSelected(true);
                        jTextFieldRG.setText(conn.rs.getString("cliente_rg"));
                        jTextFieldRG.setEnabled(false);
                        jTextFieldRazaoSocial.setVisible(false);
                        jTextFieldCPF.setText(recebeCpfCnpj);
                    } else {
                        jTextFieldRazaoSocial.setVisible(true);
                        jCheckBoxPessoaFisica.setSelected(false);
                        jTextFieldRazaoSocial.setText(conn.rs.getString("cliente_razao_social"));
                        jTextFieldCNPJ.setText(recebeCpfCnpj);
                    }

                    jTextFieldCidade.setText(conn.rs.getString("cliente_endereco_cidade"));
                    jTextFieldComplemento.setText(conn.rs.getString("cliente_endereco_complemento"));
                    jTextFieldEndereco.setText(conn.rs.getString("cliente_endereco_logradouro"));
                    jTextFieldNome.setText(conn.rs.getString("cliente_nome"));
                    jTextFieldTelefone.setText(conn.rs.getString("cliente_telefone"));
                    jTextFieldNumero.setText(conn.rs.getString("cliente_endereco_numero"));
                } else {
                }
                conn.rs.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            flag = 2;
            esquemaBotoesSalvar();
        } else {
            JOptionPane.showMessageDialog(null, "Para alterar, selecione algum item.");
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        esquemaBotoesInicio();
        limpaCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        frm_cliente = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void jCheckBoxPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPessoaFisicaActionPerformed
        mudaTipoPessoa();
    }//GEN-LAST:event_jCheckBoxPessoaFisicaActionPerformed

    private void jTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCPFFocusLost

    }//GEN-LAST:event_jTextFieldCPFFocusLost

    private void jTextFieldCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCNPJFocusLost

    }//GEN-LAST:event_jTextFieldCNPJFocusLost

    private void jTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCNPJActionPerformed
        CPF pf = new CPF(jTextFieldCPF.getText());
        CNPJ cnp = new CNPJ(jTextFieldCNPJ.getText());
        if (cnp.isCNPJ()) {
            consultaCNPJ();
        } else {
            JOptionPane.showMessageDialog(null, "Compo: CNPJ inválido");

        }
    }//GEN-LAST:event_jTextFieldCNPJActionPerformed

    private void esquemaBotoesInicio() {
        jButtonCancelar.setVisible(false);
        jButtonSalvar.setVisible(false);
        jButtonNovo.setVisible(true);
        jButtonAlterar.setVisible(true);
        jButtonLimparBusca.setVisible(false);
        CardLayout cl = (CardLayout) jPanelGeral.getLayout();
        cl.show(jPanelGeral, "consulta");
        this.setSize(755, 420);
    }

    private void esquemaBotoesSalvar() {
        if (flag == 1) {
            jCheckBoxPessoaFisica.setEnabled(true);
            jCheckBoxPessoaFisica.setSelected(true);
            jTextFieldCPF.setEnabled(true);
            jTextFieldRG.setEnabled(true);
        } 
        jButtonLimparBusca.setVisible(false);
        jButtonCancelar.setVisible(true);
        jButtonSalvar.setVisible(true);
        jButtonNovo.setVisible(false);
        jButtonAlterar.setVisible(false);
        CardLayout cl = (CardLayout) jPanelGeral.getLayout();
        cl.show(jPanelGeral, "cadastro");
        this.setSize(755, 450);
    }

    private void verificaCamposVazios() {
        CPF pf = new CPF(jTextFieldCPF.getText());
        CNPJ cnpj = new CNPJ(jTextFieldCNPJ.getText());
        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: " + jLabelNome.getText() + ", está em branco");
            jTextFieldNome.requestFocus();
            jTextFieldNome.setBackground(color);
        } else {
            jTextFieldNome.setBackground(colorPadrao);
        }
        if (jCheckBoxPessoaFisica.isSelected()) {
            if (jTextFieldCPF.getText().replaceAll("[./-]", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo: CPF, está em branco");
                jTextFieldCPF.requestFocus();
                jTextFieldCPF.setBackground(color);
            } else {
                if (pf.isCPF()) {
                    jTextFieldCPF.setBackground(colorPadrao);
                } else {
                    JOptionPane.showMessageDialog(null, "Compo: CPF, está inválido");
                    jTextFieldCPF.requestFocus();
                    jTextFieldCPF.setBackground(color);
                }
            }
            jTextFieldCNPJ.setBackground(colorPadrao);
            jTextFieldRazaoSocial.setBackground(colorPadrao);
        } else {
            if (jTextFieldCNPJ.getText().replaceAll("[./-]", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo: CNPJ, está em branco");
                jTextFieldCNPJ.requestFocus();
                jTextFieldCNPJ.setBackground(color);
            } else {
                if (cnpj.isCNPJ()) {
                    jTextFieldCNPJ.setBackground(colorPadrao);
                } else {
                    JOptionPane.showMessageDialog(null, "Compo: CNPJ, está inválido");
                    jTextFieldCNPJ.requestFocus();
                    jTextFieldCNPJ.setBackground(color);
                }
            }
            if (jTextFieldRazaoSocial.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo: Razão Social, está em branco");
                jTextFieldRazaoSocial.requestFocus();
                jTextFieldRazaoSocial.setBackground(color);
            } else {
                jTextFieldRazaoSocial.setBackground(colorPadrao);
            }
            jTextFieldCPF.setBackground(colorPadrao);
        }
        if (jTextFieldEndereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Endereço, está em branco");
            jTextFieldEndereco.requestFocus();
            jTextFieldEndereco.setBackground(color);
        } else {
            jTextFieldEndereco.setBackground(colorPadrao);
        }
        if (jTextFieldNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Número, está em branco");
            jTextFieldNumero.requestFocus();
            jTextFieldNumero.setBackground(color);
        } else {
            jTextFieldNumero.setBackground(colorPadrao);
        }
        if (jTextFieldBairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Bairro, está em branco");
            jTextFieldBairro.requestFocus();
            jTextFieldBairro.setBackground(color);
        } else {
            jTextFieldBairro.setBackground(colorPadrao);
        }
        if (jTextFieldCidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Cidade, está em branco");
            jTextFieldCidade.requestFocus();
            jTextFieldCidade.setBackground(color);
        } else {
            jTextFieldCidade.setBackground(colorPadrao);
        }
        if (jTextFieldCEP.getText().replaceAll("[./-]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: CEP, está em branco");
            jTextFieldCEP.requestFocus();
            jTextFieldCEP.setBackground(color);
        } else {
            jTextFieldCEP.setBackground(colorPadrao);
        }
        if (jTextFieldTelefone.getText().replaceAll("[(/)/-]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo: Celular, está em branco");
            jTextFieldTelefone.requestFocus();
            jTextFieldTelefone.setBackground(color);
        } else {
            jTextFieldTelefone.setBackground(colorPadrao);
        }
        if (jTextFieldNome.getBackground() == colorPadrao
                && jTextFieldCPF.getBackground() == colorPadrao
                && jTextFieldBairro.getBackground() == colorPadrao
                && jTextFieldCEP.getBackground() == colorPadrao
                && jTextFieldCidade.getBackground() == colorPadrao
                && jTextFieldEndereco.getBackground() == colorPadrao
                && jTextFieldTelefone.getBackground() == colorPadrao
                && jTextFieldNumero.getBackground() == colorPadrao
                && jTextFieldCEP.getBackground() == colorPadrao
                && jTextFieldRazaoSocial.getBackground() == colorPadrao
                && jTextFieldCNPJ.getBackground() == colorPadrao) {
            flagCamposVazios = 1;
        }
    }

    private void limpaCampos() {
        LimpaCampos.limpaCampos(jPanelCadastro.getComponents());
        LimpaCampos.limpaCampos(jPanelEndereco.getComponents());
    }

    public void atualizaTabela(String sql) {
        tableModelCliente.dados.removeAll(tableModelCliente.dados);
        conn.executaSQL(sql);
        try {
            while (conn.rs.next()) {
                ModalCliente modalQ = new ModalCliente();

                modalQ.setId(conn.rs.getInt("cliente_id"));
                modalQ.setNome(conn.rs.getString("cliente_nome"));
                modalQ.setCpfCnpj(conn.rs.getString("cliente_cpf_cnpj"));
                tableModelCliente.addRow(modalQ);

            }
            conn.rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void maiusculo() {
        jTextFieldBairro.setDocument(new Maiusculo());
        jTextFieldCidade.setDocument(new Maiusculo());
        jTextFieldComplemento.setDocument(new Maiusculo());
        jTextFieldEndereco.setDocument(new Maiusculo());
        jTextFieldNome.setDocument(new Maiusculo());
    }

    private void consultaCNPJ() {
        String retorno = null;
        Gson gson = new Gson();
        ConexaoHttp a = new ConexaoHttp();

        cnpj = jTextFieldCNPJ.getText();
        cnpj = cnpj.replaceAll("/", "");
        cnpj = cnpj.replaceAll("-", "");
        cnpj = cnpj.replaceAll("[.]", "");
        //teste
        String url = "http://www.receitaws.com.br/v1/cnpj/" + cnpj;
        try {
            flagComplemento = 1;
            retorno = a.sendGet(url);
        } catch (Exception ex) {
            flagComplemento = 2;
            JOptionPane.showMessageDialog(null, ex + "\nProvavelmente, seu cliente foi cadastrado na Receita no último mês, então não se preocupe.\nApenas preencha os dados do cliente manualmente.\nE atualize este cadastro mais tarde ");
            jTextFieldNome.requestFocus();
        }
        if (flagComplemento == 1) {
            JsonObject obj = new com.google.gson.JsonParser().parse(retorno).getAsJsonObject();

            jTextFieldRazaoSocial.setText(obj.get("nome").getAsString());
            jComboBoxUF.setSelectedItem(obj.get("uf").getAsString());
            jTextFieldBairro.setText(obj.get("bairro").getAsString());
            jTextFieldEndereco.setText(obj.get("logradouro").getAsString());
            jTextFieldCEP.setText(obj.get("cep").getAsString().replaceAll("[./-]", ""));
            jTextFieldCidade.setText(obj.get("municipio").getAsString());
            jTextFieldNome.setText(obj.get("fantasia").getAsString());
            jTextFieldNumero.setText(obj.get("numero").getAsString());
            jTextFieldComplemento.setText(obj.get("complemento").getAsString());

            ap.add(obj.get("atividade_principal").getAsJsonArray());
        } else {

        }
    }

    private void mudaTipoPessoa() {
        if (jCheckBoxPessoaFisica.isSelected() == true) {
            jTextFieldCPF.setEnabled(true);
            jTextFieldCNPJ.setEnabled(false);
            jLabelNome.setText("Nome Completo");
            jLabelRazaoSocial.setVisible(false);
            jTextFieldRazaoSocial.setVisible(false);
            jTextFieldRG.setEnabled(true);
            limpaCampos();
            jCheckBoxPessoaFisica.setSelected(true);
        } else {
            jTextFieldCPF.setEnabled(false);
            jTextFieldCNPJ.setEnabled(true);
            jLabelNome.setText("Nome Fantasia");
            jLabelRazaoSocial.setVisible(true);
            jTextFieldRazaoSocial.setVisible(true);
            jTextFieldRG.setEnabled(false);
            limpaCampos();
            jCheckBoxPessoaFisica.setSelected(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimparBusca;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxPessoaFisica;
    private javax.swing.JComboBox jComboBoxUF;
    private javax.swing.JLabel jLabeCelular;
    private javax.swing.JLabel jLabeNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCNPJ;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRazaoSocial;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JLabel jLabelVariavalBusca;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JFormattedTextField jTextFieldCEP;
    private javax.swing.JFormattedTextField jTextFieldCNPJ;
    private javax.swing.JFormattedTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JFormattedTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
