/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.conexao;
import DAO.cadastro.DAOUsuario;
import Util.CopiarArquivo;
import Util.Maiusculo;
import Util.Meios;
import Util.Verificar.VerificarPropriedades;
import Util.Verificar.VerificarUsuario;
import Visao.arquivo.frm_usuarios_senha;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class frm_login extends javax.swing.JFrame {

    conexao conexaoBD = new conexao();
    VerificarUsuario verificarUsuario = new VerificarUsuario();
    VerificarPropriedades verificarPropriedades = new VerificarPropriedades();
    CopiarArquivo copiar = new CopiarArquivo();
    PreparedStatement stmt = null;
    ResultSet rs = null;
    public String login;
    public static String loginUsuario;
    DefaultListModel MODELO;
    int enter = 0;
    String[] Codig;
    String feitaConexao = null;
    Date hoje = new Date();
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date dataBanco;
    Date dataBancoObrigacoes;
    String dateHoje;
    String tarefas;
    boolean finalizar;
    boolean cancelar;
    String usuarioLogado = null;
    boolean primeiroAcesso;
    String versao = null;
    String versaoFtp = null;
    JFrame frame = new JFrame();

    /**
     * Creates new form frm_login
     */
    public frm_login() {
        //CRIAR OS DIRETORIOS ONDE SERÃO SALVOS OS BACKUPS E OS BOLETOS
        try {
            File criarPastaNovaHotel = new File("C:\\NovaHotel");
            criarPastaNovaHotel.mkdir();
            File criarPastaBackup = new File("C:\\NovaHotel\\Backup");
            criarPastaBackup.mkdir();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar o diretorio: " + ex);
            System.out.println(ex);
        }
        // INICIO DA FUNÇÃO QUE VERIFICA OS DADOS DO ARQUIVO CONEXAO.TXT
        verificarPropriedades.carregaPropriedades();
        // FIM DA VERIFICAÇÃO E INICIO DA VERIFICAÇÃO DESSES DADOS
        if (verificarPropriedades.flag == 1) {
            initComponents();
            try {
                conexaoBD.conexao();
            } catch (SQLException ex) {
                Logger.getLogger(frm_login.class.getName()).log(Level.SEVERE, null, ex);
            }
            usuarioLogado = verificarPropriedades.login;
            // FIM DA VERIFICAÇÃO E INICIO DA VERIFICAÇÃO DESSES DADOS
            jTextFieldLogin.setDocument(new Maiusculo());
            if (usuarioLogado != null) {
                jTextFieldLogin.setText(verificarPropriedades.login);
            } else {

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelLoginSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jLabelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NovaHotel");
        getContentPane().setLayout(null);

        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("Login");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(90, 80, 50, 13);
        getContentPane().add(jTextFieldLogin);
        jTextFieldLogin.setBounds(20, 100, 190, 30);

        jLabelLoginSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginSenha.setText("Senha");
        getContentPane().add(jLabelLoginSenha);
        jLabelLoginSenha.setBounds(90, 150, 40, 13);

        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(20, 170, 190, 30);

        jButtonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Unlocked.png"))); // NOI18N
        jButtonEntrar.setToolTipText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(90, 250, 50, 40);

        jLabelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plano de Fundo 2.png"))); // NOI18N
        getContentPane().add(jLabelImagemFundo);
        jLabelImagemFundo.setBounds(-250, -100, 530, 460);

        setSize(new java.awt.Dimension(240, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        acessoSistema();
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jPasswordFieldSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            acessoSistema();
        }
    }//GEN-LAST:event_jPasswordFieldSenhaKeyReleased

    private void acessoSistema() {
        String id;
        if (jTextFieldLogin.getText().equals("ADMIN") && jPasswordFieldSenha.getText().equals("admin123")) {
            verificarUsuario.login = jTextFieldLogin.getText();
            verificarUsuario.setAdm(1);
            v_principal telaPrincipal = new v_principal();
            telaPrincipal.setVisible(true);
            this.dispose();
        } else {
            conexaoBD.executaSQL("SELECT * FROM tbl_usuario WHERE usuario_login = '" + jTextFieldLogin.getText() + "'");
            try {
                if (conexaoBD.rs.next()) {
                    id = String.valueOf(conexao.rs.getInt("usuario_id"));
                    if (conexao.rs.getString("usuario_senha") == null) {
                        frm_usuarios_senha informarSenha = new frm_usuarios_senha(jTextFieldLogin.getText(), id, "Login");
                        informarSenha.setVisible(true);
                        JOptionPane.showMessageDialog(null, "Por favor, cadastre uma senha!");
                        conexaoBD.rs.close();
                    } else {
                        DAOUsuario daoU = new DAOUsuario();
                        if (daoU.checkLogin(jTextFieldLogin.getText(), Meios.Cripto(jPasswordFieldSenha.getText()))) {

                            verificarUsuario.login = jTextFieldLogin.getText();
                            verificarUsuario.verificarLogin();
                            v_principal telaPrincipal = new v_principal();
                            telaPrincipal.setVisible(true);
                            // INCIO DA PARTE ONDE O SISTEMA IRA GRAVAR O ULTIMO USUARIO LOGADO NO SISTEMA
                            verificarPropriedades.salvaLogin(jTextFieldLogin.getText());
                            
                            //FIM DA FUNÇÃO
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Login ou senha incorreto");
                        }
                    }
                } 
            } catch (SQLException ex) {

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelImagemFundo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoginSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
