/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.conexao;
import Model.ModalData;
import Model.cadastro.ModalProduto;
import Model.table.TableModelQuantidadeProdutos;
import Util.GerenteJanelas;
import Util.Verificar.VerificarUsuario;
import Visao.arquivo.frm_cabecalho;
import Visao.cadastro.frm_cliente;
import Visao.cadastro.frm_produto;
import Visao.cadastro.frm_quarto;
import Visao.arquivo.frm_usuario;
import Visao.busca.frm_busca_clientes;
import Visao.busca.frm_busca_produtos;
import Visao.processo.frm_consulta_hospedagem;
import Visao.processo.frm_hospedagem;
import Visao.sobre.v_sobre;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import org.joda.time.DateTime;

/**
 *
 * @author Matheus
 */
public class v_principal extends javax.swing.JFrame {

    
    VerificarUsuario verificaUsuario = new VerificarUsuario();
    conexao conexao = new conexao();
    GerenteJanelas gerenteJanelas;
    ModalData modalData = new ModalData();
    Date dataHoje = new Date();
    SimpleDateFormat parser = new SimpleDateFormat("HH:mm");
    DateTime hoje = new DateTime(dataHoje);

    /**
     * Creates new form v_principal
     */
    public v_principal() {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        controleAcesso();
        this.gerenteJanelas = new GerenteJanelas(jDesktopPanePrincipal);
        jLabelLogin.setText(verificaUsuario.login);
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy");
        jLabelData.setText(formato.format(dataSistema));
        
        Timer timer = new Timer(1000, new informaHora());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jButtonCadastroCliente = new javax.swing.JButton();
        jButtonCadastroCliente1 = new javax.swing.JButton();
        jPanelUsuarioLogado = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jPanelDataHora = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemCabecalho = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jSeparatorArquivo = new javax.swing.JPopupMenu.Separator();
        jMenuItemDesconectar = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemQuartos = new javax.swing.JMenuItem();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jSeparatorCadastro1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuProcesso = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemConsultaHospedagem = new javax.swing.JMenuItem();
        jMenuItemHospedagem = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuRelatoriosArquivo = new javax.swing.JMenu();
        jMenuItemRelatoriosUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorioCadastro = new javax.swing.JMenu();
        jMenuItemRelatoriosQuartos = new javax.swing.JMenuItem();
        jMenuItemRelatoriosProdutos = new javax.swing.JMenuItem();
        jSeparatorRelatoriosCadastro = new javax.swing.JPopupMenu.Separator();
        jMenuItemRelatoriosClientes = new javax.swing.JMenuItem();
        jMenuRelatoriosProcesso = new javax.swing.JMenu();
        jMenuItemRelatoriosHospedagem = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBackup = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Woman-Suit.png"))); // NOI18N
        jButtonCadastroCliente.setToolTipText("Cadastro de Cliente");
        jButtonCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClienteActionPerformed(evt);
            }
        });

        jButtonCadastroCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bed-2 (2).png"))); // NOI18N
        jButtonCadastroCliente1.setToolTipText("Hospedar");
        jButtonCadastroCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCliente1ActionPerformed(evt);
            }
        });

        jDesktopPanePrincipal.setLayer(jButtonCadastroCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jButtonCadastroCliente1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap(668, Short.MAX_VALUE)
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastroCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jButtonCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCadastroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastroCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );

        jPanelUsuarioLogado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("jLabel1");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipo.setText("jLabel1");

        javax.swing.GroupLayout jPanelUsuarioLogadoLayout = new javax.swing.GroupLayout(jPanelUsuarioLogado);
        jPanelUsuarioLogado.setLayout(jPanelUsuarioLogadoLayout);
        jPanelUsuarioLogadoLayout.setHorizontalGroup(
            jPanelUsuarioLogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLogadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelUsuarioLogadoLayout.setVerticalGroup(
            jPanelUsuarioLogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLogadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jLabelTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDataHora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData.setText("jLabel1");

        jLabelHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setText("jLabel1");

        javax.swing.GroupLayout jPanelDataHoraLayout = new javax.swing.GroupLayout(jPanelDataHora);
        jPanelDataHora.setLayout(jPanelDataHoraLayout);
        jPanelDataHoraLayout.setHorizontalGroup(
            jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDataHoraLayout.setVerticalGroup(
            jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData)
                    .addComponent(jLabelHora))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Box-File.png"))); // NOI18N
        jMenuArquivo.setText("Arquivo");

        jMenuItemCabecalho.setText("Cabeçalho");
        jMenuItemCabecalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCabecalhoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemCabecalho);

        jMenuItemUsuario.setText("Usuários");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemUsuario);
        jMenuArquivo.add(jSeparatorArquivo);

        jMenuItemDesconectar.setText("Desconectar");
        jMenuArquivo.add(jMenuItemDesconectar);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Box-Incoming (2).png"))); // NOI18N
        jMenuCadastro.setText("Cadastro");

        jMenuItemQuartos.setText("Quartos");
        jMenuItemQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuartosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemQuartos);

        jMenuItemProdutos.setText("Produtos");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemProdutos);
        jMenuCadastro.add(jSeparatorCadastro1);

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemClientes);

        jMenuBar1.add(jMenuCadastro);

        jMenuProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Moleskine-Open.png"))); // NOI18N
        jMenuProcesso.setText("Processo");

        jMenu1.setText("Hospedagem");

        jMenuItemConsultaHospedagem.setText("Consulta Hospedagem");
        jMenuItemConsultaHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaHospedagemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultaHospedagem);

        jMenuItemHospedagem.setText("Hospedagem");
        jMenuItemHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHospedagemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemHospedagem);

        jMenuProcesso.add(jMenu1);

        jMenuBar1.add(jMenuProcesso);

        jMenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Notebook.png"))); // NOI18N
        jMenuRelatorios.setText("Relátorios");

        jMenuRelatoriosArquivo.setText("Arquivo");

        jMenuItemRelatoriosUsuarios.setText("Usuários");
        jMenuRelatoriosArquivo.add(jMenuItemRelatoriosUsuarios);

        jMenuRelatorios.add(jMenuRelatoriosArquivo);

        jMenuRelatorioCadastro.setText("Cadastro");

        jMenuItemRelatoriosQuartos.setText("Quartos");
        jMenuRelatorioCadastro.add(jMenuItemRelatoriosQuartos);

        jMenuItemRelatoriosProdutos.setText("Produtos");
        jMenuRelatorioCadastro.add(jMenuItemRelatoriosProdutos);
        jMenuRelatorioCadastro.add(jSeparatorRelatoriosCadastro);

        jMenuItemRelatoriosClientes.setText("Clientes");
        jMenuRelatorioCadastro.add(jMenuItemRelatoriosClientes);

        jMenuRelatorios.add(jMenuRelatorioCadastro);

        jMenuRelatoriosProcesso.setText("Processo");

        jMenuItemRelatoriosHospedagem.setText("Hospedagem");
        jMenuRelatoriosProcesso.add(jMenuItemRelatoriosHospedagem);

        jMenuRelatorios.add(jMenuRelatoriosProcesso);

        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Wrench.png"))); // NOI18N
        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBackup.setText("Backup");
        jMenuItemBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBackupActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBackup);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Question-Mark.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });

        jMenuItemCreditos.setText("Créditos");
        jMenuItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreditosActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemCreditos);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPanePrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(jPanelDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPanePrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        gerenteJanelas.abrirjanelas(frm_usuario.getInstancia());
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        gerenteJanelas.abrirjanelas(frm_cliente.getInstancia());
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
        gerenteJanelas.abrirjanelas(frm_produto.getInstancia());
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jMenuItemQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartosActionPerformed
        gerenteJanelas.abrirjanelas(frm_quarto.getInstancia());
    }//GEN-LAST:event_jMenuItemQuartosActionPerformed

    private void jMenuItemHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHospedagemActionPerformed
        gerenteJanelas.abrirjanelas(frm_hospedagem.getInstancia());
    }//GEN-LAST:event_jMenuItemHospedagemActionPerformed

    private void jButtonCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClienteActionPerformed
        gerenteJanelas.abrirjanelas(frm_cliente.getInstancia());
    }//GEN-LAST:event_jButtonCadastroClienteActionPerformed

    private void jButtonCadastroCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCliente1ActionPerformed
        gerenteJanelas.abrirjanelas(frm_hospedagem.getInstancia());
    }//GEN-LAST:event_jButtonCadastroCliente1ActionPerformed

    private void jMenuItemBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBackupActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed

    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jMenuItemCabecalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCabecalhoActionPerformed
        gerenteJanelas.abrirjanelas(frm_cabecalho.getInstancia());
    }//GEN-LAST:event_jMenuItemCabecalhoActionPerformed

    private void jMenuItemConsultaHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaHospedagemActionPerformed
        gerenteJanelas.abrirjanelas(frm_consulta_hospedagem.getInstancia());
    }//GEN-LAST:event_jMenuItemConsultaHospedagemActionPerformed

    private void jMenuItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreditosActionPerformed
        gerenteJanelas.abrirjanelas(v_sobre.getInstancia());
    }//GEN-LAST:event_jMenuItemCreditosActionPerformed

    private void controleAcesso() {
        if (verificaUsuario.getAdm() == 1) {
            jMenuArquivo.setVisible(true);
            jMenuCadastro.setVisible(true);
            jLabelTipo.setText("Administrador");
            jButtonCadastroCliente.setVisible(true);
        } else {
            jMenuArquivo.setVisible(false);
            jMenuCadastro.setVisible(false);
            jLabelTipo.setText("Comum");
            jButtonCadastroCliente.setVisible(false);
        }
    }

    class informaHora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar agora = Calendar.getInstance();
            jLabelHora.setText(String.format("%1$tH:%1$tM", agora));
        }
    }

    public void fechaTudo() {

    }

    public static void abrirBuscador(String tela, String sql) {
        GerenteJanelas.abrirjanelas(frm_busca_clientes.getInstancia(tela, sql));
    }

    public static void abrirBuscadorProdutos(String tela) {
        GerenteJanelas.abrirjanelas(frm_busca_produtos.getInstancia(tela));
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCliente;
    private javax.swing.JButton jButtonCadastroCliente1;
    public static javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabelData;
    public static javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemBackup;
    private javax.swing.JMenuItem jMenuItemCabecalho;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemConsultaHospedagem;
    private javax.swing.JMenuItem jMenuItemCreditos;
    private javax.swing.JMenuItem jMenuItemDesconectar;
    private javax.swing.JMenuItem jMenuItemHospedagem;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemQuartos;
    private javax.swing.JMenuItem jMenuItemRelatoriosClientes;
    private javax.swing.JMenuItem jMenuItemRelatoriosHospedagem;
    private javax.swing.JMenuItem jMenuItemRelatoriosProdutos;
    private javax.swing.JMenuItem jMenuItemRelatoriosQuartos;
    private javax.swing.JMenuItem jMenuItemRelatoriosUsuarios;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuProcesso;
    private javax.swing.JMenu jMenuRelatorioCadastro;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuRelatoriosArquivo;
    private javax.swing.JMenu jMenuRelatoriosProcesso;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanelDataHora;
    private javax.swing.JPanel jPanelUsuarioLogado;
    private javax.swing.JPopupMenu.Separator jSeparatorArquivo;
    private javax.swing.JPopupMenu.Separator jSeparatorCadastro1;
    private javax.swing.JPopupMenu.Separator jSeparatorRelatoriosCadastro;
    // End of variables declaration//GEN-END:variables
}
